#!/bin/bash
# Crete an Apache website with virtualhost

# get the website name
read -p "Enter website name "  website

mkdir /var/www/$website

# privilages to the directory
sudo chown -R $USER:$USER /var/www/$website
sudo chmod -R 755 /var/www/$website

# create sample index html
touch /var/www/$website/index.html

echo "<html><head><title>Welcome to the page </title></head><body><h1>This is a sample page created by script</h1></body></html>" > /var/www/$website/index.html

# create virtualhost
touch /etc/apache2/sites-available/$website.conf

read -p "Enter website domain ("domain-test.com") :"  domain

read -p "Enter website port :"  port

echo "
<VirtualHost *:$port>
ServerAdmin admin@sampledomain.com
ServerName $domain
ServerAlias www.$domain
DocumentRoot /var/www/$website
</VirtualHost>
" > /etc/apache2/sites-available/$website.conf

# enable website config
sudo a2ensite $website.conf

# restart apache
systemctl start apache2
sudo systemctl reload apache2
