#!/bin/bash
# Make a load testing with k6

# 0 - go to home folder
cd $HOME

# 1 - create a loadTesting folder
echo "$(tput setaf 2) creating a loadTesting folder in your HOME directory ..."
mkdir loadTesting

# 2 - create a simple script
echo "$(tput setaf 2) creating a k6 script ..."

# ask for web domain
read -p "Enter the web domain (example.com) :"  domain

touch script.js
echo "import http from 'k6/http';
import { sleep } from 'k6';

export default function() {
  http.get('http://${domain}');
  sleep(1);
}" > script.js

# 3 - run the script

# ask for number of virtual users
read -p "Enter number of virtual user :"  users

# ask for the duration of the test
read -p "Enter the duration (in minutes) of the testing :"  duration

echo "$(tput setaf 2) creating a k6 script ..."

k6 run --vus $users --duration ${duration}m script.js
