#!/bin/bash
# create an apache virtualhost

# create virtualhost
read -p "Enter the website name (example.com) :"  website

touch /etc/apache2/sites-available/$website.conf

read -p "Enter website domain ("domain-test.com") :"  domain

read -p "Enter website port :"  port

echo "
<VirtualHost *:$port>
ServerAdmin admin@sampledomain.com
ServerName $domain
ServerAlias www.$domain
DocumentRoot /var/www/$website
</VirtualHost>
" > /etc/apache2/sites-available/$website.conf

# enable website config
sudo a2ensite $website.conf

# restart apache
systemctl start apache2
sudo systemctl reload apache2

echo "remember to add the ip to your /etc/hosts file like so ==> 10.0.10.40 test-domain.local"
© 2020 GitHub, Inc.
